version: '2.0'
services:
  mysql:
    image: hypriot/rpi-mysql:latest
    container_name: mysql
    restart: always
    volumes:
       - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - "3306:3306"
volumes:
    mysql_data:
